### ISSUE TITLE
Window resizing doesn't work for SponzaPbr demo

### ISSUE THREAD

**Issue by jayrulez** [andrejnau/FlyCube#10]
There's a crash with the following log:
```
Exception thrown at 0x00007FF8E3BA4B89 in SponzaPbr.exe: Microsoft C++ exception: _com_error at memory location 0x0000001DCE2F4C68.
DXGI ERROR: IDXGIFactory::CreateSwapChain: Only one flip model swap chain can be associate with an HWND, IWindow, or composition surface at a time. ClearState() and Flush() may need to be called on the D3D11 device context to trigger deferred destruction of old swapchains. [ MISCELLANEOUS ERROR #297: ]
Exception thrown at 0x00007FF8E3BA4B89 in SponzaPbr.exe: Microsoft C++ exception: _com_error at memory location 0x0000001DCE2F4CE0.

HRESULT failed in "F:\\SponzaPbr\\3rdparty\\FlyCube\\src\\Core\\Swapchain\\DXSwapchain.cpp" @ 28
--> hr = 0x80070005
```

**Comment by andrejnau** [comment]
Thank you for reporting the issue, I will take a look.

**Comment by andrejnau** [comment]
Fixed in https://github.com/andrejnau/FlyCube/commit/285c509fae18ea1de710676d60cf1a4d6a8a6e7d

**Comment by jayrulez** [comment]
Thanks for the update. I'll test it when I get a chance.

Reading the commit, it seems this only affects the high level renderer. 

Resizing the window with vulkan in the core triangle demo failed and crashed as well. Does this commit fix that?

**Comment by andrejnau** [comment]
Yes, this changes only affects the high level renderer.

**Comment by andrejnau** [comment]
To simplify samples, I did not add window resizing handling. I'd rather forbid window resizing there.

**Comment by jayrulez** [comment]
I see. Thanks for the fix. I was able to add resizing for both my high level and low level samples.

Fix for SponzaPbr resizing confirmed.

One more question before closing. Should the window appear black while resizing for vulkan?

I observed this in my sample. However, I'm unable to test the vulkan implementation with SponzaPbr as it does not run:
https://github.com/andrejnau/SponzaPbr/issues/1

**Comment by andrejnau** [comment]
If it happens during windows resizing, just draw 1 frame from OnResize callback.
