### ISSUE TITLE
DX-Specific code in abstraction layer

### ISSUE THREAD

**Issue by jayrulez** [andrejnau/FlyCube#11]
Have you thought about a fix for this yet?

https://github.com/andrejnau/FlyCube/blob/master/src/Render/ObjectCache/ObjectCache.cpp#L116

**Comment by andrejnau** [comment]
The high-level abstraction layer needs rework. It is a legacy from https://github.com/andrejnau/SponzaPbr, and has some problems and limitations. I was focused on the low-level abstraction layer (https://github.com/andrejnau/FlyCube/tree/master/src/Core), now it is almost finished and I will probably start rewriting other components soon.

**Comment by jayrulez** [comment]
Thanks for the update.

Just to give you some context about what I am doing with FlyCube.

I have ported the FlyCube low level API to ezEngine (github.com/ezEngine/ezEngine)

I have reorganized the libraries a bit:
The abstraction is now in a single lib(https://github.com/jayrulez/ezEngine/tree/flycube/Code/Engine/RHI), VK implementation is in its own lib(https://github.com/jayrulez/ezEngine/tree/flycube/Code/Engine/RHIVulkan) and DX is in its own lib(https://github.com/jayrulez/ezEngine/tree/flycube/Code/Engine/RHIDX12) as well.
The shader compiler and backend shader reflection classes are in the hlsl compiler lib(https://github.com/jayrulez/ezEngine/tree/flycube/Code/Engine/RHIShaderCompilerHLSL).

I removed shader compilation from the render api and use the hlsl compiler to compile the shaders then pass the byte code and reflection information to the shaderbase construction.

I've also removed the dependency on gli formats and added my custom format enum (https://github.com/jayrulez/ezEngine/blob/flycube/Code/Engine/RHI/RHIDLL.h#L24).

The goal here is to get Vulkan support into ezEngine without doing everything from scratch (I'm not an expert at low level graphics stuff).

I've ported the CoreTriangle sample and that works the same as it does in FlyCube with both Vulkan and DX12: https://github.com/jayrulez/ezEngine/tree/flycube/Code/Samples/RHISampleLowLevel

The high level renderer should work as well but I won't bother with that for now since you are rewriting it.

The only problem I've run into so far is resizing the window.

It behaves just the same as FlyCube though (same crash) so I'm sure it is not a porting bug.

My next step is to try to rebase the ez renderer on your abstraction.

**Comment by andrejnau** [comment]
Fixed in https://github.com/andrejnau/FlyCube/commit/32e5c3fa3ebec738e9ee8c29eb1735b15f110861
