### ISSUE TITLE
Feature Request: Change VULKAN_SUPPORT from variable, to option

### ISSUE THREAD

**Issue by DavidArppe** [andrejnau/FlyCube#15]
Hi! I love what you're doing,

One thing I've noticed is that, I can't seem to disable vulkan support, from a higher-level cmake project. At the moment, the way it's defined, I am not sure it's possible. It's written as:

`set(VULKAN_SUPPORT ON)`

However, it might be worthwhile changing it to 
`option(VULKAN_SUPPORT "Vulkan Support" ON)`

This would be similar to how GLFW exposes their BUILD_EXAMPLES variable, and how you are able to disable examples being built from your cmake/3rdparty/glfw cmake file.

Thanks! :)
David

**Comment by andrejnau** [comment]
Hi! Thanks for the feature request. I have replaced variables with options in https://github.com/andrejnau/FlyCube/commit/d35671a8001a451e7f423cc8fd8819cf6fa95895
