### ISSUE TITLE
Indirect Drawing question

### ISSUE THREAD

**Issue by THISISAGOODNAME** [andrejnau/FlyCube#2]
Is there an API like DrawIndexedIndirect or ExecuteIndirect ?

**Comment by andrejnau** [comment]
There is no such API yet. I'll see how to do it for Vulkan and DirectX 12.

**Comment by THISISAGOODNAME** [comment]
That is great!

**Comment by andrejnau** [comment]
`DrawIndirectCount/DrawIndexedIndirectCount` have been added in https://github.com/andrejnau/FlyCube/commit/443318a71dd45f48c25df559993631985baba2b8
