### ISSUE TITLE
Vk 1.2.170 has some error

### ISSUE THREAD

**Issue by runner0353** [andrejnau/FlyCube#9]
when i  run  indirect example  ， the application throw [an](url) exception

- 
![hlsl](https://user-images.githubusercontent.com/36179001/113533924-ca69d800-9601-11eb-99fc-53eb76662987.PNG)
![hlsl](https://user-images.githubusercontent.com/36179001/113533933-d05fb900-9601-11eb-8eff-f6856e12a8e6.PNG)

**Comment by andrejnau** [comment]
If you skip these exceptions will the application continue to work? `hlsl::Exception` is an internal exception that was thrown and caught in `dxcompiler.dll`. I can't reproduce `std::out_of_range`. Could you please provide the call stack?

**Comment by runner0353** [comment]
![indirect](https://user-images.githubusercontent.com/36179001/113540723-50424f00-9613-11eb-966e-14997d29a4d6.PNG)

**Comment by andrejnau** [comment]
Could you check if it works with https://github.com/andrejnau/FlyCube/commit/ed823d89fd2854368622058b00bf17024616d233 ?

**Comment by runner0353** [comment]
![DispatchIndirect](https://user-images.githubusercontent.com/36179001/113562868-74188b80-9639-11eb-9af3-1372da8756d3.PNG)
only dispatchindirect example has  an exception  ,others  no problem

**Comment by andrejnau** [comment]
It is thrown from `d3d12sdklayers.dll`, so skip it if the application continue to work after this exception and d3d12 debug layer doesn't report anything.

**Comment by runner0353** [comment]
thank you, no question
